---
- name: Create hello.txt with OS version information
  hosts: myhosts
  become: true  # Ensure tasks run with elevated privileges if necessary

  vars:
    target_directory: "/home/wysetimepcc/wyse-edge/setup/ansible"
    target_file: "{{ target_directory }}/hello.txt"
    default_message: "OS version is not explicitly handled"

  tasks:
    - name: Ensure target directory exists
      file:
        path: "{{ target_directory }}"
        state: directory
        mode: '0755'

    - name: Set OS version message based on Ansible facts
      set_fact:
        os_version_message: >-
          {% if ansible_distribution_version == "24.04" %}
            OS version is Ubuntu 24.04
          {% elif ansible_distribution_version == "22.04" %}
            OS version is Ubuntu 22.04
          {% elif ansible_distribution_version == "20.04" %}
            OS version is Ubuntu 20.04
          {% else %}
            {{ default_message }}
          {% endif %}

    - name: Create hello.txt with OS version message
      copy:
        content: "{{ os_version_message }}"
        dest: "{{ target_file }}"
        mode: '0644'

    - name: Display OS version message
      debug:
        msg: "{{ os_version_message }}"
