- name: Create hello.txt with "Hello, World!"
  hosts: localhost  # Replace with your target hosts if necessary
  become: false      # Set to true if required

  tasks:
    - name: Create hello.txt with content
      copy:
        content: "Hello, World!\n"
        dest: "/home/wysetimepcc/wyse-edge/setup/ansible/hello.txt"
        mode: '0644'

    - name: Confirm file creation
      debug:
        msg: "hello.txt has been successfully created with the content 'Hello, World!'"
