- name: Create hello.txt with Hello World
  hosts: myhosts
  become: True

  tasks:
  - name: Create hello.txt and write Hello World
    copy:
      content: "Hello, World!"
      dest: /home/wysetimepcc/wyse-edge/setup/hello.txt
      mode: '0644'
