- name: Create hello.txt and output Ubuntu version
  hosts: myhosts
  become: True

  tasks:
  - name: Create hello.txt and write Hello World
    copy:
      content: "Hello, World!"
      dest: /home/wysetimepcc/wyse-edge/setup/ansible/hello.txt
      state: touch
      mode: '0644'

  - name: Get Ubuntu version
    command: lsb_release -d
    register: ubuntu_version_output

  - name: Display Ubuntu version
    debug:
      var: ubuntu_version_output.stdout
